# Generated by Django 5.0.7 on 2024-08-04 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=250, unique=True, verbose_name='Equipe')),
                ('encarregado', models.CharField(max_length=100, verbose_name='Encarregado')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor')),
                ('data_criacao', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('data_modificacao', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
