# Generated by Django 5.0.7 on 2024-08-04 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Equipe',
        ),
    ]
